---
title: "Merge the Data"
author: "memrekus"
date: "6/2/2022"
output: html_document
---


__Merging the RNAseq, miRNAseq and Subtype data__


```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```


#Load Libraries


```{r}

library("TCGAbiolinks")
library("limma")
library("edgeR")
library("glmnet")
library("factoextra")
library("FactoMineR")
library("caret")
library("SummarizedExperiment")
library("gplots")
library("survival")
library("survminer")
library("RColorBrewer")
library("gProfileR")
library("genefilter")
library("data.table")
library("dplyr")
library("tidyverse")
library("Rsamtools")
library("rtracklayer")
library("AnnotationHub")
library("ggplot2")

```


#Loading the prepared data


```{r}

load(file='Data_RNA.rda')

load(file='Data_miRNA.rda')

load(file='Data_Subtype.rda')

```


#Binding the data to each other


```{r}

total<-merge(x=Data_RNA,y=Data_Subtype,by=0, all=TRUE)

totall <- total[,-1]

rownames(totall) <- total[,1]

total2<-merge(totall, Data_miRNA, by = 0, all.x=TRUE)

totall<-total2[,-1]

rownames(totall)<-total2[,1]

rm(total2)

save(totall,file = "totall.Rda")

all(colnames(Data_miRNA) %in% colnames(totall))

length(intersect(rownames(totall), rownames(Data_miRNA)))

length(intersect(rownames(totall), rownames(Data_RNA)))

all(rownames(Data_miRNA) %in% rownames(totall))

```


#Remove 


```{r}

rm(Data_miRNA,Data_RNA,Data_Subtype)

```

